# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties
# ===================================================================


log:
  level:
    root: INFO

spring:
  main:
    banner-mode: 'off'
  jmx:
    enabled: true
  application:
    name: ContentLogicApplication

elasticsearch:
  host: ${AWS_ELASTICSEARCH_ENDPOINT}
  port:
  region: ${AWS_REGION}
  service-name: ${AWS_ELASTICSEARCH_NAME}

amazon:
  dynamodb:
    region: ${AWS_REGION}
    # the following will be used in dev only
    endpoint:
  aws:
    accesskey:
    secretkey:

cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: true
    region:
      static: ${AWS_REGION}

contentsTableName: contents-table-staging